# Generated by Django 3.0.14 on 2021-08-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
