# Generated by Django 3.0.14 on 2021-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
